AudioPlayerConstants = {
  AUDIO_PLAYING: "AUDIO_PLAYING",
  AUDIO_PAUSED: "AUDIO_PAUSED",
  AUDIO_ENDED: "AUDIO_ENDED",
  AUDIO_CURRENT_TIME_RECEIVED: "AUDIO_CURRENT_TIME_RECEIVED",
  AUDIO_VOLUME_RECEIVED: "AUDIO_VOLUME_RECEIVED",
  AUDIO_DURATION_RECEIVED: "AUDIO_DURATION_RECEIVED",
  PLAY_AUDIO: "PLAY_AUDIO",
  PAUSE_AUDIO: "PAUSE_AUDIO",
  CHANGE_VOLUME_TO: "CHANGE_VOLUME_TO",
  RESET_AUDIO_PLAYER_REQUESTS: "RESET_AUDIO_PLAYER_REQUESTS"
};

module.exports = AudioPlayerConstants;
